apiVersion: batch/v1
kind: Job
metadata:
  name: swiggy-clone-job
spec:
  template:
    spec:
      containers:
      - name: swiggy-clone-job
        image: yash5090/swiggy-clone:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
