apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-clone-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: swiggy-clone
  template:
    metadata:
      labels:
        app: swiggy-clone
    spec:
      containers:
        - name: swiggy-clone
          image: yash5090/swiggy-clone:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
